---
title: "Phosphorylations figures"
author: COW and VS
output: html_document
---

Load the required libraries.
```{r message=FALSE}
require(dplyr) # for table manipulation
require(tidyr) # for table manipulation
require(cowplot) # for plotting
```

Read in the previously generated data table:
```{r}
mods_summary <- read.csv("./GeneratedDataFiles/phosphorylations.csv")
```


## any +80 Dalton mod
```{r fig.width=10, fig.height=4}
# extract the +80 modification
mods <- filter(mods_summary, mod=="any_p80")

# absolute fraction
plot1 <- ggplot(mods, aes(x=time, y=100*frac.mod.abs, color=biol.rep)) +
  scale_x_log10(breaks = c(3, 4, 5, 6, 8, 24, 48, 168, 336)) +
  ylim(0, .05) + 
  geom_point() +
  geom_line() +
  ylab("Percent modified peptides") +
  xlab("Time (hours)") +
  scale_color_discrete(name = "Biol. repeat")

plot2 <- ggplot(mods, aes(x=time, y=odds.mod.other, color=biol.rep)) +
  scale_x_log10(breaks = c(3, 4, 5, 6, 8, 24, 48, 168, 336)) +
  scale_y_log10(breaks = c(.01, .02, .03, .04, .05, .06, .07, .08, .09, .1, .2, .3, .4, .5, .6, .7, .8, .9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10),
                labels = c("0.01", "", "0.03", "", "", "", "", "", "", "0.1", "", "0.3", "", "0.5", "", "", "", "", "1.0", "", "3.0", "", "", "", "", "", "", "10.0"),
                limits = c(.01, 10.)) + 
  geom_point() +
  geom_line() +
  ylab("Odds +80 Da / other") +
  xlab("Time (hours)") +
  scale_color_discrete(name = "Biol. repeat")

plot_grid(plot1, plot2, labels = c("A", "B"))
```

Behavior over time:
```{r}
perc.model <- lm(frac.mod.abs ~ log(time), data=mods)
summary(perc.model)
odds.model <- lm(log(odds.mod.other) ~ log(time), data=mods)
summary(odds.model)
```

## any +98 Dalton mod
```{r fig.width=10, fig.height=4}
# extract the +98 modification
mods <- filter(mods_summary, mod=="any_p98")

# absolute fraction
plot1 <- ggplot(mods, aes(x=time, y=100*frac.mod.abs, color=biol.rep)) +
  scale_x_log10(breaks = c(3, 4, 5, 6, 8, 24, 48, 168, 336)) +
  ylim(0, .02) + 
  geom_point() +
  geom_line() +
  ylab("Percent modified peptides") +
  xlab("Time (hours)") +
  scale_color_discrete(name = "Biol. repeat")

plot2 <- ggplot(mods, aes(x=time, y=odds.mod.other, color=biol.rep)) +
  scale_x_log10(breaks = c(3, 4, 5, 6, 8, 24, 48, 168, 336)) +
  scale_y_log10(breaks = c(.008, .009, .01, .02, .03, .04, .05, .06, .07, .08, .09, .1, .2, .3, .4, .5, .6, .7, .8, .9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10),
                labels = c("", "", "0.01", "", "0.03", "", "", "", "", "", "", "0.1", "", "0.3", "", "0.5", "", "", "", "", "1.0", "", "3.0", "", "", "", "", "", "", "10.0"),
                limits = c(.008, 10.)) + 
  geom_point() +
  geom_line() +
  ylab("Odds +98 Da / other") +
  xlab("Time (hours)") +
  scale_color_discrete(name = "Biol. repeat")

plot_grid(plot1, plot2, labels = c("A", "B"))
```

Behavior over time:
```{r}
perc.model <- lm(frac.mod.abs ~ log(time), data=mods)
summary(perc.model)
odds.model <- lm(log(odds.mod.other) ~ log(time), data=mods)
summary(odds.model)
```



## S+80 or T/Y+98 Dalton mods
```{r fig.width=10, fig.height=4}
# extract the modification
mods <- filter(mods_summary, mod=="S_p80_TY_p98")

# absolute fraction
plot1 <- ggplot(mods, aes(x=time, y=100*frac.mod.abs, color=biol.rep)) +
  scale_x_log10(breaks = c(3, 4, 5, 6, 8, 24, 48, 168, 336)) +
  ylim(0, .05) + 
  geom_point() +
  geom_line() +
  ylab("Percent modified peptides") +
  xlab("Time (hours)") +
  scale_color_discrete(name = "Biol. repeat")

plot2 <- ggplot(mods, aes(x=time, y=odds.mod.other, color=biol.rep)) +
  scale_x_log10(breaks = c(3, 4, 5, 6, 8, 24, 48, 168, 336)) +
  scale_y_log10(breaks = c(.01, .02, .03, .04, .05, .06, .07, .08, .09, .1, .2, .3, .4, .5, .6, .7, .8, .9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10),
                labels = c("0.01", "", "0.03", "", "", "", "", "", "", "0.1", "", "0.3", "", "0.5", "", "", "", "", "1.0", "", "3.0", "", "", "", "", "", "", "10.0"),
                limits = c(.01, 10.)) + 
  geom_point() +
  geom_line() +
  ylab("Odds S+80, T+98, Y+98 Da / other") +
  xlab("Time (hours)") +
  scale_color_discrete(name = "Biol. repeat")

plot_grid(plot1, plot2, labels = c("A", "B"))
```

Behavior over time:
```{r}
perc.model <- lm(frac.mod.abs ~ log(time), data=mods)
summary(perc.model)
odds.model <- lm(log(odds.mod.other) ~ log(time), data=mods)
summary(odds.model)
```