---
title: "Analysis of Oxidation proteins"
author: COW and VS
output: html_document
---

Load the required libraries.
```{r message=FALSE}
require(dplyr) # for table manipulation
require(tidyr) # for table reshaping
```


A function that takes a data frame with cleaned-up PSM output from MODa as input and calculates counts of specific modifications we are interested in.
```{r}
OxidizedProteinList <- function(PSM_data)
{
  write_to_log("Counting Oxidized Proteins")

  # Count the total number of unmodified peptides and peptides with any sort of modification
  PSM_data %>%group_by(Protein)%>%summarize(Oxidized_Peptides = sum(na.omit(Modification == 16)), Non_Oxidized_Peptides = sum(!na.omit(Modification == 16))) -> Oxidized_Proteins
 
    #return
    Oxidized_Proteins
}
```


```{r}
source("./utils.R") # for function readCSVFileList() used below
write_to_log("Running script `ProteinList_Oxidations.Rmd`", append = FALSE)

# read the information about the samples
samples <- read.csv("../DataAnnotations/samples.csv")
# turn to list
sample.list <- as.list(as.character(samples$sample))
names(sample.list) <- samples$sample

write_to_log("Reading data")
PSMdata.list <- readCSVFileList(sample.list, "_PSM_mods.csv", "./GeneratedDataFiles/PSMHits")

# next, count all the mods
mod_count.list <- lapply(PSMdata.list, OxidizedProteinList)
# and combine into one data frame
ProteinOxidations <- make_data_frame_from_list(mod_count.list)

# combine with other info about samples
ProtList_summary <- inner_join(samples, ProteinOxidations, by = "sample")

# and save
write.csv(ProtList_summary, "./GeneratedDataFiles/OxidizedProteinList.csv", row.names = FALSE)
```

#Combine all the oxidations at all time points into one big file


Read in the previously generated data table:
```{r}
OxiProtList <- read.csv("./GeneratedDataFiles/OxidizedProteinList.csv")


OxiProtList%>%group_by(Protein)%>%summarize(OxiAll = sum(na.omit(Oxidized_Peptides)), NonOxiAll = sum(na.omit(Non_Oxidized_Peptides)), OxiPercent = 100*OxiAll/(OxiAll+NonOxiAll))->OxiPercentList

sortOxiPercent<-OxiPercentList[with(OxiPercentList, order(-OxiPercent)), ]
head(sortOxiPercent, 15)
```

