---
title: "Analysis of N-terminal acetylations"
author: COW and VS
output: html_document
---

Load the required libraries.
```{r message=FALSE}
require(dplyr) # for table manipulation
require(tidyr) # for table reshaping
```


A function that takes a data frame with cleaned-up PSM output from MODa as input and calculates counts of specific modifications we are interested in.
```{r}
ProteinNumber <- function(PSM_data)
{
  write_to_log("Counting Oxidation mods")

  # Group oxidized peptides w.r.t AA
  
  PSM_data%>%group_by(time)%>%summarize(ProteinNumbers = sum(na.omit(Protein)))->Prots

 
    #return
    Prots
}
```


```{r}
source("./utils.R") # for function readCSVFileList() used below
write_to_log("Running script `AA_distribution_Oxidations.Rmd`", append = FALSE)

# read the information about the samples
samples <- read.csv("../DataAnnotations/samples.csv")
# turn to list
sample.list <- as.list(as.character(samples$sample))
names(sample.list) <- samples$sample

write_to_log("Reading data")
PSMdata.list <- readCSVFileList(sample.list, "_PSM_mods.csv", "./GeneratedDataFiles/PSMHits")

# next, count all the mods
mod_count.list <- lapply(PSMdata.list, ProteinNumber)
# and combine into one data frame
PC <- make_data_frame_from_list(mod_count.list)

# combine with other info about samples
ProtList_summary <- inner_join(samples, PC, by = "sample")

# and save
write.csv(ProtList_summary, "./GeneratedDataFiles/ProtList.csv", row.names = FALSE)
```

#Combine all the oxidation protein hits into one and analyze


Read in the previously generated data table:
```{r}
## loads the frequencies of amino acid n-term acetylations at ALL time points
ProtFreq <- read.csv("./GeneratedDataFiles/ProtList.csv")
## lists the top few hits
head(ProtFreq)
## count up the frequencies of the amino-acids that get oxidized (for the combined datasets)
##AAFreqOxiAll<-AAFreqOxi%>%group_by(Modified.aa)%>%summarize(TotalOxiCount = sum(Oxidized_Peptides))
## sort the hits
##sortTotalOxidizedPeptides<-AAFreqOxiAll[with(AAFreqOxiAll, order(-TotalOxiCount)), ]
## List them (Cysteine is the least oxidized, but expected because it is CAPPED and fixed modification seems to work well !)
##head(sortTotalOxidizedPeptides, 6)
```

