---
title: "counting peptides"
author: "Claus Wilke and VS"
date: "June 27, 2015"
output: html_document
---

Required libraries
```{r}
require(stringr) # for string manipulation
require(dplyr) # for table manipulation
require(tidyr) # for table reshaping
```


Read in the raw files 
```{r}
StoreMODaDataAsDataFrame<-function(sample, data_folder)
{
  # input filenames
  file_a <- file.path(data_folder, paste(sample, "a_MODa_PSMs.id.txt", sep=''))
  file_b <- file.path(data_folder, paste(sample, "b_MODa_PSMs.id.txt", sep=''))

# read raw files
peptides_a <- read.table(file_a, header = TRUE, stringsAsFactors = FALSE)
peptides_b <- read.table(file_b, header = TRUE, stringsAsFactors = FALSE)
# combine
peptides <- rbind(peptides_a, peptides_b)    

#extract all the base peptides (remove any +number or -number elements)
Base.Peptide <- factor(str_replace(peptides$Peptide, "[\\+\\-]\\d+", ""))
# extract all the modifications (+number or -number elements)
Modification <- as.numeric(str_extract(peptides$Peptide, "[\\+\\-]\\d+"))
# extract all AAs (amino acids) that get modified
Modified.aa <- str_extract(str_extract(peptides$Peptide, "[A-Z.][\\+\\-]\\d+"), '[A-Z.]')
# extract the position with respect to peptide where modification occurs
Modified.pos <- data.frame(str_locate(peptides$Peptide, "[A-Z.][\\+\\-]\\d+"))$start-2
PeptideStartWRTprotein.pos=str_extract(peptides$PeptidePosition,'[0-9]+')

# add all this information to peptides table
peptides <- data.frame(peptides, Base.Peptide, Modification, Modified.aa, Modified.pos,PeptideStartWRTprotein.pos)

head(peptides)

# First, we want to treate any and no mods separately from specific mods. So let's do those first.
peptides %>% group_by(Base.Peptide) %>%
  summarize( unmod = sum(is.na(Modification)),
             anymod = sum(!is.na(Modification))) -> peptide.anymod.counts

# now the specific mods
mods <- as.list(c(-200:-1, 1:200))
# the following code uses the .dots argument and summarize_ to work around
# non-standard evaluation, as described here:
# http://cran.r-project.org/web/packages/dplyr/vignettes/nse.html
counts.list <- lapply(mods, 
                      function(i){
                        peptides %>% group_by(Base.Peptide) %>%
                          summarize_( .dots = setNames(list(~sum(na.omit(Modification) == i)), paste("mod", i, sep='')))
                      }
                      )

# now combine everything into one table
peptide.mod.counts <- Reduce(inner_join, c(list(peptide.anymod.counts)
, counts.list))

head(peptide.anymod.counts)
head(peptide.mod.counts)
}
```

We can also use it to easily read in multiple samples and combine them:
```{r}
# create a list of all sample names from MURI_7 to MURI_33
sample_list <- as.list(paste("MURI_", 9:10, sep=''))
# read all corresponding data tables
data_list <- lapply(sample_list, StoreMODaDataAsDataFrame, data_folder = "../../ProcessedData/MODa_output/PSMHits")
head(data_list)
saveRDS(data_list, file="PeptideData.rds")
```

Now try to load the datafile
```{r}
#Use load function
data_list_load=readRDS("PeptideData.rds")
head(data_list_load)
```