---
title: "Extract peptide mods"
author: COW and VS
output: html_document
---

Load the required libraries.
```{r message=FALSE}
require(stringr) # for string manipulation
require(dplyr) # for table manipulation
require(tidyr) # for table reshaping
```

Function that reads raw MODa output and returns it in a format that is easier to process in R.
```{r}
cleanMODaData <- function(sample, data_folder)
{
  write_to_log("Reading data from sample", sample)
  # input filenames
  file_a <- file.path(data_folder, paste(sample, "a_MODa_PSMs.id.txt", sep=''))
  file_b <- file.path(data_folder, paste(sample, "b_MODa_PSMs.id.txt", sep=''))

  # read raw files
  peptides_a <- read.table(file_a, header = TRUE, stringsAsFactors = FALSE)
  peptides_b <- read.table(file_b, header = TRUE, stringsAsFactors = FALSE)
  # combine
  peptides <- rbind(peptides_a, peptides_b)    

  #extract all the base peptides (remove any +number or -number elements)
  Base.Peptide <- factor(str_replace(peptides$Peptide, "[\\+\\-]\\d+", ""))
  # extract all the modifications (+number or -number elements)
  Modification <- as.numeric(str_extract(peptides$Peptide, "[\\+\\-]\\d+"))
  # extract all AAs (amino acids) that get modified
  Modified.aa <- str_extract(str_extract(peptides$Peptide, "[A-Z.][\\+\\-]\\d+"), '[A-Z.]')
  # extract the position with respect to peptide where modification occurs
  Modified.pos <- data.frame(str_locate(peptides$Peptide, "[A-Z.][\\+\\-]\\d+"))$start-2
  # extract the start position of the peptide relative to the protein
  PeptideStart <- as.numeric(str_extract(peptides$PeptidePosition,'[0-9]+'))

  # add all this information to peptides table
  peptides <- data.frame(peptides, Base.Peptide, Modification, Modified.aa, 
                         Modified.pos, PeptideStart)
  # return data frame
  peptides
}
```

Function that takes a data frame with cleaned-up PSM output from MODa as input and counts the
various types of modifications.
```{r}
countMods <- function(PSM_data, min_mod = -200, max_mod = 200)
{
  write_to_log("Counting modifications between", min_mod, "and", max_mod)
  
  # First, we want to treate any and no mods separately from specific mods. So let's do
  # those first.
  PSM_data %>% group_by(Base.Peptide) %>%
    summarize( unmod = sum(is.na(Modification)),
               anymod = sum(!is.na(Modification))) -> anymod.counts
 
  # now the specific mods
  mods <- as.list(c(min_mod:-1, 1:max_mod))
  # the following code uses the .dots argument and summarize_ to work around
  # non-standard evaluation, as described here:
  # http://cran.r-project.org/web/packages/dplyr/vignettes/nse.html
  counts.list <- lapply(mods, 
                       function(i){
                         PSM_data %>% group_by(Base.Peptide) %>%
                            summarize_( .dots = setNames(list(~sum(na.omit(Modification) == i)),
                                                         paste("mod", i, sep='')))
                        })

  # now combine everything into one table
  mod_counts <- Reduce(function(x, y) inner_join(x, y, by = "Base.Peptide"),
                       c(list(anymod.counts), counts.list))
  #return
  mod_counts
}
```


```{r}
source("./utils.R") # for function writeCSVFromList() used below
write_to_log("Running script `extract_peptide_mods.Rmd`", append = FALSE)

# read the information about the samples
samples <- read.csv("samples.csv")
# turn to list
sample.list <- as.list(as.character(samples$sample))
names(sample.list) <- samples$sample

# now read in all the data and clean up
PSMdata.list <- lapply(sample.list, cleanMODaData, "../ProcessedData/MODa_output/PSMHits/")
# we could write these out, but it's not clear that that is useful at this time
# so we skip this for now
#writeDelimFromList(PSMdata.list, "_PSM_mods.csv", "./GeneratedDataFiles/PSMHits")

# next, count all the mods
mod_count.list <- lapply(PSMdata.list, countMods, -200, 200)
writeCSVFromList(mod_count.list, "_PSM_mod_counts.csv", "./GeneratedDataFiles/PSMHits")
```


